bin/maacota : src/mascota.cpp include/Mascota.hpp include/Entrenador.hpp
echo "Compilando Mascota"
rm bin/mascota
g++ src/mascota.cpp -o bin/pacman -I include

bin/pacman : src/pacman.cpp
g++ src/ pacman.cpp -o bin/mascota